сделал тултип
js-tasks-ru/htmlcss-20220616_fed-sav pull request #11
Opened 2022-07-05 21:25 UTC by fedsav

2022-07-05 21:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-06 10:35 UTC, GSemikozov requested changes

2022-07-06 10:35 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    display: flex;
все лишнее со строки 3 и до 6 - надо удалить

2022-07-06 10:35 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
всплывашку позиционируем сразу через абсолют

2022-07-14 07:54 UTC, GSemikozov requested changes

2022-07-14 07:54 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    padding-top: 13px;
достаточно ли паддинга только сверху?

2022-07-14 07:54 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left: -52px;
почему именно такие координаты для left + bottom? советую посмотреть как мы это делали на лекции и самое главное - почему ;)

2022-07-15 19:17 UTC, GSemikozov approved these changes

2022-07-15 19:17 UTC, merged