03-01 button task done
js-tasks-ru/htmlcss-20220616_fed-sav pull request #3
Opened 2022-06-21 21:09 UTC by fedsav

2022-06-22 21:53 UTC, GSemikozov requested changes

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <div class="button">
структурно неправильно: эта обертка может быть какой угодно, но точно не button

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +            <button class="button__elem button__elem-primary-enabled">Primary</button>
именно вот этому семантическому элементу добавляется класс .button.

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__elem {
это будет .button

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
фиксировать ширину блока не нужно

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 10px;
марджины на уровне блока нельзя

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
не хватает паддингов и стилей для оформления текста

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__elem-primary-enabled {
.button_primary

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__elem-primary-disabled {
.button_disabled

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__elem-primary-disabled {
элементам disabled лучше задавать pointer-events: none чтобы не было возможности взаимодействовать с таким элементом

2022-06-22 21:53 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__elem-secondary-enabled {
тут и ниже - по аналогии

2022-06-23 14:22 UTC, GSemikozov requested changes

2022-06-23 14:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btnBlock {
другие блоки здесь не описываем, если принципиально нужны эти стили, их можно перенести в тег style хтмл страницы с решением

2022-06-23 14:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
не хватает font-family

2022-06-23 14:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary {
для всех типов еще нужно добавить хотя бы :hover

2022-06-23 14:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_disabled {
лучше сразу использовать встроенный :disabled вместо класса

2022-06-23 14:22 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +            <button class="button button_primary button_disabled">Primary disabled</button>
и тогда здесь вместо класса атрибут disabled

2022-06-23 17:57 UTC, fedsav commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
обновил шрифты

2022-06-23 17:58 UTC, fedsav commented on 03-lection1/01-button/button.css
> +.button_primary {
добавил hover для primary secondary alternate кнопок

2022-06-23 17:58 UTC, fedsav commented on 03-lection1/01-button/button.css
> +.button_disabled {
описал :disabled, добавил атрибуты

2022-06-23 17:58 UTC, fedsav commented on 03-lection1/01-button/index.html
> +            <button class="button button_primary button_disabled">Primary disabled</button>
добавил атрибуты

2022-06-23 18:41 UTC, GSemikozov requested changes

2022-06-23 18:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +:disabled {
.button:disabled

2022-06-23 18:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-26 19:33 UTC, GSemikozov requested changes

2022-06-26 19:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button:disabled {
здесь должен быть класс .button )

2022-06-26 21:22 UTC, fedsav commented on 03-lection1/01-button/button.css
> +button:disabled {
+

2022-06-27 15:37 UTC, GSemikozov approved these changes

2022-06-27 15:37 UTC, merged