04 02 skeleton
js-tasks-ru/htmlcss-20220616_fed-sav pull request #7
Opened 2022-06-26 12:40 UTC by fedsav

Сделал скелетон

2022-06-26 12:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-26 21:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-27 10:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-27 16:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-28 18:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-28 18:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 13:58 UTC, GSemikozov requested changes

2022-07-04 13:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                    <picture class="skeleton__pic"></picture>
во здесь этот тег будет неоправданно использовать - внутри-то собственно картинок и нет ) поэтому - просто div

2022-07-04 13:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                        <div class="skeleton__first-line"></div>
у скелетона 1 элемент line, который переиспользуется в нескольких местах и отличается только шириной, что можно регулировать за счет модификаторов (skeleton__p это тоже просто линии, skeleton__line + нужный модификатор например skeleton__line_short)

2022-07-04 13:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-height: 192px;
ограничители ширины и высоты не нужны

2022-07-04 13:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid #ACB5BD;
цвет возьмем из переменных

2022-07-04 13:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px;
общие паддинги лучше сразу вынести на уровень блока

2022-07-04 13:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину линий лучше задавать в процентах

2022-07-04 20:13 UTC, fedsav commented on 04-lection2/02-skeleton/index.html
> +                    <picture class="skeleton__pic"></picture>
+

2022-07-04 20:19 UTC, fedsav commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid #ACB5BD;
+

2022-07-04 20:19 UTC, fedsav commented on 04-lection2/02-skeleton/skeleton.css
> +    max-height: 192px;
+

2022-07-14 07:47 UTC, GSemikozov approved these changes

2022-07-14 07:47 UTC, merged