сделал модалку
js-tasks-ru/htmlcss-20220616_fed-sav pull request #9
Opened 2022-07-01 20:54 UTC by fedsav

2022-07-01 20:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-01 21:55 UTC, GSemikozov requested changes

2022-07-01 21:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-open {
это не элемент модалки + в БЭМ стараемся не использовать id )

2022-07-01 21:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal-open__text {
с учетом коммента выше, стоит отметить, что классы не по БЭМ. Должно быть так:
.modal {}
.modal__window {}
.modal__close {}
.modal__text {}
.modal__title {}

2022-07-01 21:55 UTC, GSemikozov requested changes

2022-07-01 21:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background: #C4C4C4;
блок Модалка должен позиционироваться через fixed + растягиваться на всю ширину / высоту страницы и фон задаем через rgba полупрозрачным

2022-07-02 08:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-02 10:45 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +#modal-open {
+

2022-07-02 10:45 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +.modal-open__text {
+

2022-07-02 10:45 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +    background: #C4C4C4;
+

2022-07-02 10:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 20:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 20:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 17:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-09 19:30 UTC, GSemikozov requested changes

2022-07-09 19:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
в блока .modal не нужно описывать другие блоки (.button), тем более что у нас уже есть компонент Кнопка

2022-07-09 19:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    height: 100vh;
width: 100vw лучше тоже указать

2022-07-09 19:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    padding: 40px 40px 40px 47px;
паддинги нужны скорее на уровне .modal__window

2022-07-13 18:07 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +    height: 100vh;
+

2022-07-13 18:07 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +    padding: 40px 40px 40px 47px;
+

2022-07-13 18:08 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +.button {
+

2022-07-14 07:52 UTC, GSemikozov requested changes

2022-07-14 07:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    display: flex;
по умолчанию ведь display: none )

2022-07-14 07:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    padding: 30px 0 0 40px;
точно надо? или там текст центрирован горизонтально?

2022-07-14 07:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    padding: 30px 0 0 40px;
не совсем понимаю зачем такие паддинги здесь у текста и выше у заголовка - общие паддинги у окна проставлены, остается лишь отступ между заголовком и текстом сделать, через марджин либо у заголовка либо у текста
<img width="531" alt="Screenshot 2022-07-14 at 10 50 32" src="https://user-images.githubusercontent.com/6191270/178930880-965ec35a-450d-4521-8f47-ec1306cc4329.png">

2022-07-14 17:31 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +    display: flex;
+

2022-07-14 17:31 UTC, fedsav commented on 05-lection3/02-modal/modal.css
> +    padding: 30px 0 0 40px;
+

2022-07-15 19:17 UTC, GSemikozov requested changes

2022-07-15 19:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: 40px 40px 47px 40px;
а теперь не совсем понимаю зачем нам эти марджины? мы ведь и так через родителя выравниваем элемент по середине.

2022-11-09 21:20 UTC, closed without merging